CREATE TABLE individual (
    individualid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lastname VARCHAR(45) NOT NULL,
    firstname VARCHAR(45) NOT NULL,
    mi VARCHAR(45),
    email VARCHAR(45) NOT NULL,
    birthday DATE NOT NULL,
    gender CHAR(1) NOT NULL CHECK (gender IN ('M', 'F')),
    facebook_url VARCHAR(45),
    pic_filename VARCHAR(45) NOT NULL,
    undertaking BOOLEAN NOT NULL
);

CREATE TABLE mobile (
    mobilenum VARCHAR(20) PRIMARY KEY,
    individualid INTEGER NOT NULL REFERENCES individual(individualid) ON DELETE CASCADE
);

CREATE TABLE homeowner (
    homeownerid INTEGER PRIMARY KEY REFERENCES individual(individualid) ON DELETE CASCADE,
    residency_start DATE,
    membership BOOLEAN NOT NULL,
    isresident BOOLEAN NOT NULL
);

CREATE TABLE resident (
    residentid INTEGER PRIMARY KEY REFERENCES individual(individualid) ON DELETE CASCADE,
    renter BOOLEAN NOT NULL,
    rel_homeowner VARCHAR(45) NOT NULL,
    authorized BOOLEAN NOT NULL,
    last_update TIMESTAMP NOT NULL
);

CREATE TABLE homeowner_addinfo (
    homeownerid INTEGER PRIMARY KEY REFERENCES homeowner(homeownerid) ON DELETE CASCADE,
    add2_streetno VARCHAR(20),
    add2_street VARCHAR(45),
    add2_brgy VARCHAR(45),
    add2_city VARCHAR(45),
    add2_province VARCHAR(45),
    add2_mapx VARCHAR(45),
    add2_mapy VARCHAR(45),
    email2 VARCHAR(45)
);

CREATE TABLE property (
    propertycode VARCHAR(6) PRIMARY KEY,
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    size INTEGER NOT NULL,
    turnover_date DATE NOT NULL
);

CREATE TABLE household (
    householdid INTEGER PRIMARY KEY,
    propertycode VARCHAR(6) NOT NULL UNIQUE REFERENCES property(propertycode) ON DELETE CASCADE
);

CREATE TABLE payment (
    orno INTEGER PRIMARY KEY,
    amount NUMERIC(10, 2) NOT NULL
);

CREATE TABLE resident_id (
    cardno INTEGER PRIMARY KEY,
    request_date DATE NOT NULL,
    request_reason VARCHAR(45) NOT NULL,
    issue_date DATE NOT NULL,
    hoa_officer VARCHAR(45) NOT NULL,
    orno INTEGER REFERENCES payment(orno),
    residentid INTEGER REFERENCES resident(residentid),
    status CHAR(1) NOT NULL CHECK (status IN ('A', 'L', 'C'))
);

CREATE TABLE hoa (
    hoaname VARCHAR(100) PRIMARY KEY,
    office_streetno VARCHAR(20) NOT NULL,
    office_street VARCHAR(45) NOT NULL,
    office_brgy VARCHAR(45) NOT NULL,
    office_city VARCHAR(45) NOT NULL,
    office_province VARCHAR(45) NOT NULL,
    office_region VARCHAR(45) NOT NULL,
    office_zip VARCHAR(45) NOT NULL,
    office_mapx VARCHAR(45) NOT NULL,
    office_mapy VARCHAR(45) NOT NULL,
    year_est INTEGER NOT NULL,
    website VARCHAR(100),
    subd_name VARCHAR(45),
    monthly_dues INTEGER
);

CREATE TABLE hoa_docs (
    submission_type INTEGER PRIMARY KEY,
    doc_name VARCHAR(200) NOT NULL,
    submission_date TIMESTAMP
);

CREATE TABLE hoa_submissions (
    hoa_hoaname VARCHAR(100) NOT NULL REFERENCES hoa(hoaname) ON DELETE CASCADE,
    hoa_docs_submission_type INTEGER NOT NULL REFERENCES hoa_docs(submission_type),
    submission_date DATE NOT NULL,
    PRIMARY KEY (hoa_hoaname, hoa_docs_submission_type, submission_date)
);

CREATE TABLE hoa_officer (
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    hoaname VARCHAR(100) NOT NULL REFERENCES hoa(hoaname),
    position VARCHAR(100) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    elec_date DATE,
    elec_venue VARCHAR(45) NOT NULL,
    elec_quorum BOOLEAN NOT NULL,
    elec_witnessname VARCHAR(100) NOT NULL,
    elec_witnessmobile VARCHAR(20) NOT NULL,
    avail_mon VARCHAR(2) NOT NULL CHECK (avail_mon IN ('M', 'A', 'NA')),
    avail_tue VARCHAR(2) NOT NULL CHECK (avail_tue IN ('M', 'A', 'NA')),
    avail_wed VARCHAR(2) NOT NULL CHECK (avail_wed IN ('M', 'A', 'NA')),
    avail_thu VARCHAR(2) NOT NULL CHECK (avail_thu IN ('M', 'A', 'NA')),
    avail_fri VARCHAR(2) NOT NULL CHECK (avail_fri IN ('M', 'A', 'NA')),
    avail_sat VARCHAR(2) NOT NULL CHECK (avail_sat IN ('M', 'A', 'NA')),
    avail_sun VARCHAR(2) NOT NULL CHECK (avail_sun IN ('M', 'A', 'NA')),
    PRIMARY KEY (homeownerid, position, start_date)
);

CREATE TABLE asset (
    assetid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    description VARCHAR(100),
    acq_date DATE NOT NULL,
    forrent BOOLEAN NOT NULL,
    value REAL NOT NULL,
    type CHAR(1) NOT NULL CHECK (type IN ('P', 'E', 'F', 'O')),
    status VARCHAR(2) NOT NULL CHECK (status IN ('W', 'DE', 'FR', 'FD', 'DI')),
    location VARCHAR(45) NOT NULL,
    location_mapx VARCHAR(45) NOT NULL,
    location_mapy VARCHAR(45) NOT NULL
);

CREATE TABLE asset_activity (
    activityid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assetid INTEGER NOT NULL REFERENCES asset(assetid),
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    orno INTEGER REFERENCES payment(orno),
    activity_date DATE NOT NULL,
    description VARCHAR(100) NOT NULL,
    sched_start DATE,
    sched_end DATE,
    actual_start DATE,
    actual_end DATE,
    status CHAR(1) NOT NULL CHECK (status IN ('S', 'O', 'C', 'D'))
);

CREATE TABLE asset_transfer (
    transferid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assetid INTEGER NOT NULL REFERENCES asset(assetid),
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    orno INTEGER REFERENCES payment(orno),
    sched_date DATE NOT NULL,
    actual_date DATE,
    from_location VARCHAR(45) NOT NULL,
    to_location VARCHAR(45) NOT NULL,
    person_name VARCHAR(100) NOT NULL,
    person_mobile VARCHAR(20) NOT NULL,
    status CHAR(1) NOT NULL CHECK (status IN ('S', 'O', 'C', 'D'))
);

CREATE TABLE asset_rental (
    rentalid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assetid INTEGER NOT NULL REFERENCES asset(assetid),
    residentid INTEGER NOT NULL REFERENCES resident(residentid),
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    orno INTEGER REFERENCES payment(orno),
    reservation_date DATE NOT NULL,
    rental_date DATE,
    discount REAL,
    status VARCHAR(2) NOT NULL CHECK (status IN ('RV', 'C', 'OR', 'RT', 'D')),
    inspection_details VARCHAR(100),
    return_officer INTEGER REFERENCES homeowner(homeownerid),
    damage_fee REAL
);

CREATE TABLE donation (
    donationid INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    donor_name VARCHAR(100) NOT NULL,
    donor_address VARCHAR(200) NOT NULL,
    homeownerid INTEGER NOT NULL REFERENCES homeowner(homeownerid),
    donation_date DATE NOT NULL,
    description VARCHAR(200)
);
